export const FETCH_INVOICES = "FETCH_INVOICES";
export const FETCH_INVOICES_SUCCESS = "FETCH_INVOICES_SUCCESS";
export const FETCH_INVOICES_FAILURE = "FETCH_INVOICES_FAILURE";

export const CHANGE_DATE = "CHANGE_DATE";
export const CHANGE_CUSTOMER_NAME = "CHANGE_CUSTOMER_NAME";
export const CHANGE_SALESPERSON_NAME = "CHANGE_SALESPERSON_NAME";
export const CHANGE_PAYMENT_TYPE = "CHANGE_PAYMENT_TYPE";
export const CHANGE_NOTES = "CHANGE_NOTES";

export const CREATE_INVOICE = "CREATE_INVOICE";
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";
export const CREATE_INVOICE_FAILURE = "CREATE_INVOICE_FAILURE";

export const CHANGE_ITEMS = "CHANGE_ITEMS";
