export const ADD_INVOICE = "ADD_INVOICE";
export const GET_INVOICES = "GET_INVOICES";
export const GET_GRAPH_DATA = "GET_GRAPH_DATA";

export const FETCH_INVOICES = "FETCH_INVOICES";
export const FETCH_INVOICES_SUCCESS = "FETCH_INVOICES_SUCCESS";
export const FETCH_INVOICES_FAILURE = "FETCH_INVOICES_FAILURE";
